// Code generated by protoc-gen-go.
// source: examples/examplepb/stream.proto
// DO NOT EDIT!

package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/serviceconfig"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import grpc_gateway_examples_sub "github.com/grpc-ecosystem/grpc-gateway/examples/sub"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for StreamService service

type StreamServiceClient interface {
	BulkCreate(ctx context.Context, opts ...grpc.CallOption) (StreamService_BulkCreateClient, error)
	List(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (StreamService_ListClient, error)
	BulkEcho(ctx context.Context, opts ...grpc.CallOption) (StreamService_BulkEchoClient, error)
}

type streamServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamServiceClient(cc *grpc.ClientConn) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) BulkCreate(ctx context.Context, opts ...grpc.CallOption) (StreamService_BulkCreateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StreamService_serviceDesc.Streams[0], c.cc, "/grpc.gateway.examples.examplepb.StreamService/BulkCreate", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceBulkCreateClient{stream}
	return x, nil
}

type StreamService_BulkCreateClient interface {
	Send(*ABitOfEverything) error
	CloseAndRecv() (*google_protobuf1.Empty, error)
	grpc.ClientStream
}

type streamServiceBulkCreateClient struct {
	grpc.ClientStream
}

func (x *streamServiceBulkCreateClient) Send(m *ABitOfEverything) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceBulkCreateClient) CloseAndRecv() (*google_protobuf1.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf1.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) List(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (StreamService_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StreamService_serviceDesc.Streams[1], c.cc, "/grpc.gateway.examples.examplepb.StreamService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_ListClient interface {
	Recv() (*ABitOfEverything, error)
	grpc.ClientStream
}

type streamServiceListClient struct {
	grpc.ClientStream
}

func (x *streamServiceListClient) Recv() (*ABitOfEverything, error) {
	m := new(ABitOfEverything)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) BulkEcho(ctx context.Context, opts ...grpc.CallOption) (StreamService_BulkEchoClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StreamService_serviceDesc.Streams[2], c.cc, "/grpc.gateway.examples.examplepb.StreamService/BulkEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceBulkEchoClient{stream}
	return x, nil
}

type StreamService_BulkEchoClient interface {
	Send(*grpc_gateway_examples_sub.StringMessage) error
	Recv() (*grpc_gateway_examples_sub.StringMessage, error)
	grpc.ClientStream
}

type streamServiceBulkEchoClient struct {
	grpc.ClientStream
}

func (x *streamServiceBulkEchoClient) Send(m *grpc_gateway_examples_sub.StringMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceBulkEchoClient) Recv() (*grpc_gateway_examples_sub.StringMessage, error) {
	m := new(grpc_gateway_examples_sub.StringMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for StreamService service

type StreamServiceServer interface {
	BulkCreate(StreamService_BulkCreateServer) error
	List(*google_protobuf1.Empty, StreamService_ListServer) error
	BulkEcho(StreamService_BulkEchoServer) error
}

func RegisterStreamServiceServer(s *grpc.Server, srv StreamServiceServer) {
	s.RegisterService(&_StreamService_serviceDesc, srv)
}

func _StreamService_BulkCreate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).BulkCreate(&streamServiceBulkCreateServer{stream})
}

type StreamService_BulkCreateServer interface {
	SendAndClose(*google_protobuf1.Empty) error
	Recv() (*ABitOfEverything, error)
	grpc.ServerStream
}

type streamServiceBulkCreateServer struct {
	grpc.ServerStream
}

func (x *streamServiceBulkCreateServer) SendAndClose(m *google_protobuf1.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceBulkCreateServer) Recv() (*ABitOfEverything, error) {
	m := new(ABitOfEverything)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).List(m, &streamServiceListServer{stream})
}

type StreamService_ListServer interface {
	Send(*ABitOfEverything) error
	grpc.ServerStream
}

type streamServiceListServer struct {
	grpc.ServerStream
}

func (x *streamServiceListServer) Send(m *ABitOfEverything) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamService_BulkEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).BulkEcho(&streamServiceBulkEchoServer{stream})
}

type StreamService_BulkEchoServer interface {
	Send(*grpc_gateway_examples_sub.StringMessage) error
	Recv() (*grpc_gateway_examples_sub.StringMessage, error)
	grpc.ServerStream
}

type streamServiceBulkEchoServer struct {
	grpc.ServerStream
}

func (x *streamServiceBulkEchoServer) Send(m *grpc_gateway_examples_sub.StringMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceBulkEchoServer) Recv() (*grpc_gateway_examples_sub.StringMessage, error) {
	m := new(grpc_gateway_examples_sub.StringMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkCreate",
			Handler:       _StreamService_BulkCreate_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _StreamService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BulkEcho",
			Handler:       _StreamService_BulkEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor2,
}

func init() { proto.RegisterFile("examples/examplepb/stream.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x90, 0xb1, 0x4a, 0x03, 0x31,
	0x18, 0xc7, 0x39, 0x15, 0xd1, 0x13, 0x97, 0x0c, 0x0e, 0xe7, 0x50, 0x2c, 0x82, 0x55, 0x24, 0x5f,
	0xab, 0x9b, 0x9b, 0x95, 0x0e, 0x82, 0xe2, 0xd0, 0xcd, 0xa5, 0x24, 0xc7, 0x77, 0x69, 0xe8, 0x5d,
	0x12, 0x92, 0x5c, 0xb5, 0xe0, 0xe4, 0xe8, 0xda, 0x17, 0xf1, 0x5d, 0x7c, 0x05, 0x1f, 0x44, 0x7a,
	0xb9, 0xde, 0xd4, 0xd2, 0xba, 0x25, 0x7c, 0xff, 0xe4, 0xfb, 0xfd, 0x7f, 0x71, 0x0b, 0xdf, 0x59,
	0x61, 0x72, 0x74, 0x50, 0x1f, 0x0c, 0x07, 0xe7, 0x2d, 0xb2, 0x82, 0x1a, 0xab, 0xbd, 0x26, 0x2d,
	0x61, 0x4d, 0x4a, 0x05, 0xf3, 0xf8, 0xc6, 0x66, 0x74, 0x99, 0xa6, 0x4d, 0x3a, 0x79, 0x14, 0x5a,
	0x8b, 0x1c, 0xa9, 0xd0, 0x39, 0x53, 0x82, 0x6a, 0x2b, 0x40, 0xa0, 0xaa, 0x1e, 0x43, 0x18, 0x31,
	0x23, 0x1d, 0x30, 0x23, 0xc1, 0xa1, 0x9d, 0xca, 0x14, 0x53, 0xad, 0x32, 0x29, 0x80, 0x29, 0xa5,
	0x3d, 0xf3, 0x52, 0x2b, 0x17, 0x76, 0x25, 0xa7, 0x21, 0x0f, 0xd5, 0x8d, 0x97, 0x19, 0x60, 0x61,
	0xfc, 0xac, 0x1e, 0x5e, 0xaf, 0x20, 0x65, 0x23, 0x2e, 0xfd, 0x48, 0x67, 0x23, 0x9c, 0xa2, 0x9d,
	0xf9, 0xb1, 0x54, 0xa2, 0x4e, 0x27, 0x4d, 0xda, 0x95, 0x1c, 0x0a, 0x74, 0x8e, 0x09, 0x0c, 0xb3,
	0x9b, 0xef, 0xdd, 0xf8, 0x78, 0x58, 0x75, 0x1c, 0x06, 0x20, 0xf2, 0x15, 0xc5, 0x71, 0xbf, 0xcc,
	0x27, 0x0f, 0x16, 0x99, 0x47, 0xd2, 0xa3, 0x1b, 0x4a, 0xd3, 0xfb, 0xbe, 0xf4, 0x2f, 0xd9, 0xa0,
	0xd9, 0x9a, 0x9c, 0xd0, 0x5a, 0xc3, 0x92, 0x9d, 0x0e, 0x16, 0xec, 0x6d, 0xf8, 0xfc, 0xf9, 0x9d,
	0xef, 0x5c, 0xb6, 0xcf, 0x61, 0xda, 0x5b, 0x82, 0xaf, 0xc2, 0x06, 0x5e, 0xe6, 0x93, 0xbb, 0xe8,
	0xaa, 0x13, 0x91, 0x8f, 0x78, 0xef, 0x49, 0x3a, 0x4f, 0xd6, 0x7c, 0x99, 0xfc, 0x9f, 0xae, 0x7d,
	0x51, 0x51, 0x9c, 0x91, 0xd6, 0x06, 0x8a, 0x6e, 0x44, 0xe6, 0x51, 0x7c, 0xb0, 0x50, 0x31, 0x48,
	0xc7, 0x9a, 0x74, 0xd6, 0xac, 0x72, 0x25, 0xa7, 0x43, 0x6f, 0xa5, 0x12, 0xcf, 0xc1, 0x6c, 0xb2,
	0x75, 0x72, 0x7b, 0x23, 0x98, 0x8e, 0x75, 0x65, 0xa4, 0x1b, 0xf5, 0x8f, 0x5e, 0x0f, 0x9b, 0x7a,
	0x7c, 0xbf, 0x12, 0x72, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x17, 0x9e, 0x06, 0xbc, 0x02,
	0x00, 0x00,
}
